version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: src/TicketFlow.Web/Dockerfile
    depends_on:
      - mssql
      - redis
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports: 
      - "1433:1433"
  redis:
    image: "redis:alpine"